import { Providers } from "@/providers";
import { Montserrat } from "next/font/google";
import "../globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: {locale}
}) {
  return (
    <html lang={locale}>
      <body className={montserrat.className} props={locale}>
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );
}
